[package]
org = "heshanp"
name = "phonix_wrapper"
version = "0.1.0"
distribution = "2201.12.8"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "com.example"
artifactId = "graalpy-phonix-wrapper"
version = "0.1.0"
path = "./lib/native.jar"
